Repository vespa-engine/vespa, pull requests merged in 2022-04, with the labels that each got.

#22100 Remove compatibility serialisation for revisions, and add (de-) for job types
  controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/JobType.java
  controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/RevisionId.java
  controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/TesterCloud.java
  controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/organization/DeploymentFailureMails.java
  controller-api/src/test/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/JobTypeTest.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/deployment/DeploymentStatus.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/deployment/JobController.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/deployment/RunList.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/ApplicationSerializer.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/BufferedLogStore.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/CuratorDb.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/RunSerializer.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/JobControllerApiHandlerHelper.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/deployment/DeploymentApiHandler.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/deployment/DeploymentTriggerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/persistence/ApplicationSerializerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/persistence/RunSerializerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/restapi/application/responses/dev-us-east-1-log-first-part.json
Labels: DO NOT MERGE

#22125 Jonmv/serialize job type with zone
  controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/JobId.java
  controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/JobType.java
  controller-api/src/test/java/com/yahoo/vespa/hosted/controller/api/integration/deployment/JobTypeTest.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/deployment/DeploymentStatus.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/deployment/RetriggerEntrySerializer.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/deployment/Run.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/ApplicationSerializer.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/CuratorDb.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/NotificationsSerializer.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/RunSerializer.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/deployment/BadgeApiHandler.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/filter/AthenzRoleFilter.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/deployment/DeploymentContext.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/maintenance/CloudTrialExpirerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/maintenance/JobRunnerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/persistence/NotificationsSerializerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/persistence/RunSerializerTest.java
  controller-server/src/test/java/com/yahoo/vespa/hosted/controller/restapi/deployment/responses/root.json
  vespajlib/src/test/java/ai/vespa/http/HttpURLTest.java
Labels: DO NOT MERGE

#22198 Use new controller lock scheme by default
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/CuratorDb.java
  controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/MockCuratorDb.java
Labels: DO NOT MERGE

#22253 Require jdk17 and maven 3.6
  hosted-tenant-base/pom.xml
  tenant-base/pom.xml
Labels: DO NOT MERGE, REBASE AND MERGE

#22273 Fix build meta JSON MERGEOK
  bundle-plugin/src/test/java/com/yahoo/container/plugin/mojo/GenerateSourcesMojoTest.java
  vespa-application-maven-plugin/src/main/java/com/yahoo/container/plugin/mojo/ApplicationMojo.java
Labels: DO NOT MERGE

#22327 GC compression inside document
  config-model/src/main/javacc/IntermediateParser.jj
  config-model/src/main/javacc/SDParser.jj
Labels: REBASE AND MERGE

#22331 allow empty string
  container-search/src/main/java/com/yahoo/search/dispatch/rpc/RpcProtobufFillInvoker.java
Labels: REBASE AND MERGE

#22337 Remove 'jetty' attribute from container element
  config-model/src/main/java/com/yahoo/vespa/model/container/xml/ContainerModelBuilder.java
  config-model/src/main/resources/schema/containercluster.rnc
  config-model/src/test/java/com/yahoo/vespa/model/container/xml/JettyContainerModelBuilderTest.java
Labels: REBASE AND MERGE

#22356 Enable filtering 'strict-mode' by default
  config-model/src/main/java/com/yahoo/vespa/model/container/http/Http.java
  config-model/src/test/java/com/yahoo/vespa/model/container/http/StrictFilteringTest.java
Labels: REBASE AND MERGE
